# Generated by Django 3.1.3 on 2020-11-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_dinner_platters_regular_pizza_silican_pizza_subs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinner_platters',
            name='price_one',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='dinner_platters',
            name='price_two',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='regular_pizza',
            name='price_one',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='regular_pizza',
            name='price_two',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='silican_pizza',
            name='price_one',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='silican_pizza',
            name='price_two',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='subs',
            name='price_one',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='subs',
            name='price_two',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
