# Generated by Django 3.1.3 on 2020-12-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20201127_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='dinner_platters',
            old_name='price_one',
            new_name='large',
        ),
        migrations.RenameField(
            model_name='dinner_platters',
            old_name='price_two',
            new_name='small',
        ),
        migrations.RenameField(
            model_name='regular_pizza',
            old_name='price_one',
            new_name='large',
        ),
        migrations.RenameField(
            model_name='regular_pizza',
            old_name='price_two',
            new_name='small',
        ),
        migrations.RenameField(
            model_name='silican_pizza',
            old_name='price_one',
            new_name='large',
        ),
        migrations.RenameField(
            model_name='silican_pizza',
            old_name='price_two',
            new_name='small',
        ),
        migrations.RenameField(
            model_name='subs',
            old_name='price_one',
            new_name='large',
        ),
        migrations.RenameField(
            model_name='subs',
            old_name='price_two',
            new_name='small',
        ),
    ]
